version: '3'

services:
  front-end:
      build:
        context: ./
        dockerfile: ./Dockerfile
      restart: always
      ports:
        - "4173:4173"
      deploy:
        mode: replicated
        replicas: 1

